# Generated by Django 3.2.12 on 2023-03-27 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MastodonServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_base_url', models.CharField(max_length=100)),
                ('client_id', encrypted_model_fields.fields.EncryptedCharField()),
                ('client_secret', encrypted_model_fields.fields.EncryptedCharField()),
            ],
        ),
        migrations.CreateModel(
            name='MastodonUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('userId', models.CharField(max_length=100, null=True)),
                ('token', encrypted_model_fields.fields.EncryptedCharField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='user.mastodonserver')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mastodon', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
